/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovS3VsaWFoL0JlbGFqYXJBbmd1bGFyL0luc3RhbGxBbmd1bGFyL1BlbXJvZ3JhbWFuLVdlYi1MYW5qdXQvUHJha3Rpa3VtIDEyL3NyYy9hcHAvYWRtaW4vYWRtaW4uY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9LdWxpYWgvQmVsYWphckFuZ3VsYXIvSW5zdGFsbEFuZ3VsYXIvUGVtcm9ncmFtYW4tV2ViLUxhbmp1dC9QcmFrdGlrdW0gMTIvc3JjL2FwcC9hZG1pbi9hZG1pbi5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
