/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './admin.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/common';
import * as i3 from './admin.component';
import * as i4 from '../services/order.service';
const styles_AdminComponent:any[] = [i0.styles];
export const RenderType_AdminComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_AdminComponent,data:{}});
function View_AdminComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'li',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(1,(null as any),['','']))],(null as any),(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,1,0,currVal_0);
  });
}
export function View_AdminComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(1,0,
      (null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),
      ['Admin'])),(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(4,0,(null as any),
      (null as any),1,'h2',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['Orders'])),
      (_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(7,0,(null as any),
          (null as any),4,'ul',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n  '])),
      (_l()(),i1.ɵand(16777216,(null as any),(null as any),1,(null as any),View_AdminComponent_1)),
      i1.ɵdid(10,802816,(null as any),0,i2.NgForOf,[i1.ViewContainerRef,i1.TemplateRef,
          i1.IterableDiffers],{ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i1.ɵted(-1,
          (null as any),['\n']))],(_ck,_v) => {
    var _co:i3.AdminComponent = _v.component;
    const currVal_0:any = _co.orders;
    _ck(_v,10,0,currVal_0);
  },(null as any));
}
export function View_AdminComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-admin',
      ([] as any[]),(null as any),(null as any),(null as any),View_AdminComponent_0,
      RenderType_AdminComponent)),i1.ɵdid(1,114688,(null as any),0,i3.AdminComponent,
      [i4.OrderService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const AdminComponentNgFactory:i1.ComponentFactory<i3.AdminComponent> = i1.ɵccf('app-admin',
    i3.AdminComponent,View_AdminComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovS3VsaWFoL0JlbGFqYXJBbmd1bGFyL0luc3RhbGxBbmd1bGFyL1BlbXJvZ3JhbWFuLVdlYi1MYW5qdXQvUHJha3Rpa3VtIDEyL3NyYy9hcHAvYWRtaW4vYWRtaW4uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0t1bGlhaC9CZWxhamFyQW5ndWxhci9JbnN0YWxsQW5ndWxhci9QZW1yb2dyYW1hbi1XZWItTGFuanV0L1ByYWt0aWt1bSAxMi9zcmMvYXBwL2FkbWluL2FkbWluLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L0t1bGlhaC9CZWxhamFyQW5ndWxhci9JbnN0YWxsQW5ndWxhci9QZW1yb2dyYW1hbi1XZWItTGFuanV0L1ByYWt0aWt1bSAxMi9zcmMvYXBwL2FkbWluL2FkbWluLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovS3VsaWFoL0JlbGFqYXJBbmd1bGFyL0luc3RhbGxBbmd1bGFyL1BlbXJvZ3JhbWFuLVdlYi1MYW5qdXQvUHJha3Rpa3VtIDEyL3NyYy9hcHAvYWRtaW4vYWRtaW4uY29tcG9uZW50LnRzLkFkbWluQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG48aDE+QWRtaW48L2gxPlxuPGgyPk9yZGVyczwvaDI+XG48dWw+XG4gIDxsaSAqbmdGb3I9XCJsZXQgb3JkZXIgb2Ygb3JkZXJzXCI+e3sgb3JkZXIgfX08L2xpPlxuPC91bD4iLCI8YXBwLWFkbWluPjwvYXBwLWFkbWluPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0lFO01BQUEsd0VBQWlDO2FBQUE7SUFBQTtJQUFBOzs7O29CQUpuQywwQ0FDQTtNQUFBO01BQUEsNENBQUk7TUFBQSxZQUFVLDBDQUNkO01BQUE7TUFBQSw4QkFBSTtNQUFXLDBDQUNmO1VBQUE7VUFBQSw4QkFBSTtNQUNGO2FBQUE7NEJBQUEseUNBQWlEO1VBQUE7O0lBQTdDO0lBQUosWUFBSSxTQUFKOzs7O29CQ0pGO01BQUE7K0JBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
