/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './no-access.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './no-access.component';
const styles_NoAccessComponent:any[] = [i0.styles];
export const RenderType_NoAccessComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NoAccessComponent,data:{}});
export function View_NoAccessComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(1,0,
      (null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),
      ['Access Denied']))],(null as any),(null as any));
}
export function View_NoAccessComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-no-access',
      ([] as any[]),(null as any),(null as any),(null as any),View_NoAccessComponent_0,
      RenderType_NoAccessComponent)),i1.ɵdid(1,114688,(null as any),0,i2.NoAccessComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const NoAccessComponentNgFactory:i1.ComponentFactory<i2.NoAccessComponent> = i1.ɵccf('app-no-access',
    i2.NoAccessComponent,View_NoAccessComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovS3VsaWFoL0JlbGFqYXJBbmd1bGFyL0luc3RhbGxBbmd1bGFyL1BlbXJvZ3JhbWFuLVdlYi1MYW5qdXQvUHJha3Rpa3VtIDEyL3NyYy9hcHAvbm8tYWNjZXNzL25vLWFjY2Vzcy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovS3VsaWFoL0JlbGFqYXJBbmd1bGFyL0luc3RhbGxBbmd1bGFyL1BlbXJvZ3JhbWFuLVdlYi1MYW5qdXQvUHJha3Rpa3VtIDEyL3NyYy9hcHAvbm8tYWNjZXNzL25vLWFjY2Vzcy5jb21wb25lbnQudHMiLCJuZzovLy9EOi9LdWxpYWgvQmVsYWphckFuZ3VsYXIvSW5zdGFsbEFuZ3VsYXIvUGVtcm9ncmFtYW4tV2ViLUxhbmp1dC9QcmFrdGlrdW0gMTIvc3JjL2FwcC9uby1hY2Nlc3Mvbm8tYWNjZXNzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovS3VsaWFoL0JlbGFqYXJBbmd1bGFyL0luc3RhbGxBbmd1bGFyL1BlbXJvZ3JhbWFuLVdlYi1MYW5qdXQvUHJha3Rpa3VtIDEyL3NyYy9hcHAvbm8tYWNjZXNzL25vLWFjY2Vzcy5jb21wb25lbnQudHMuTm9BY2Nlc3NDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbjxoMT5BY2Nlc3MgRGVuaWVkPC9oMT4iLCI8YXBwLW5vLWFjY2Vzcz48L2FwcC1uby1hY2Nlc3M+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLDBDQUNBO01BQUE7TUFBQSw0Q0FBSTtNQUFBOzs7b0JDREo7TUFBQTtrQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
