/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovS3VsaWFoL0JlbGFqYXJBbmd1bGFyL0luc3RhbGxBbmd1bGFyL1BlbXJvZ3JhbWFuLVdlYi1MYW5qdXQvUHJha3Rpa3VtIDEyL3NyYy9hcHAvbm8tYWNjZXNzL25vLWFjY2Vzcy5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0t1bGlhaC9CZWxhamFyQW5ndWxhci9JbnN0YWxsQW5ndWxhci9QZW1yb2dyYW1hbi1XZWItTGFuanV0L1ByYWt0aWt1bSAxMi9zcmMvYXBwL25vLWFjY2Vzcy9uby1hY2Nlc3MuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
