/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovS3VsaWFoL0JlbGFqYXJBbmd1bGFyL0luc3RhbGxBbmd1bGFyL1BlbXJvZ3JhbWFuLVdlYi1MYW5qdXQvUHJha3Rpa3VtIDEyL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovS3VsaWFoL0JlbGFqYXJBbmd1bGFyL0luc3RhbGxBbmd1bGFyL1BlbXJvZ3JhbWFuLVdlYi1MYW5qdXQvUHJha3Rpa3VtIDEyL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
