/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './signup.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './signup.component';
const styles_SignupComponent:any[] = [i0.styles];
export const RenderType_SignupComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_SignupComponent,data:{}});
export function View_SignupComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  signup works!\n'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_SignupComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-signup',
      ([] as any[]),(null as any),(null as any),(null as any),View_SignupComponent_0,
      RenderType_SignupComponent)),i1.ɵdid(1,114688,(null as any),0,i2.SignupComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const SignupComponentNgFactory:i1.ComponentFactory<i2.SignupComponent> = i1.ɵccf('app-signup',
    i2.SignupComponent,View_SignupComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovS3VsaWFoL0JlbGFqYXJBbmd1bGFyL0luc3RhbGxBbmd1bGFyL1BlbXJvZ3JhbWFuLVdlYi1MYW5qdXQvUHJha3Rpa3VtIDEyL3NyYy9hcHAvc2lnbnVwL3NpZ251cC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovS3VsaWFoL0JlbGFqYXJBbmd1bGFyL0luc3RhbGxBbmd1bGFyL1BlbXJvZ3JhbWFuLVdlYi1MYW5qdXQvUHJha3Rpa3VtIDEyL3NyYy9hcHAvc2lnbnVwL3NpZ251cC5jb21wb25lbnQudHMiLCJuZzovLy9EOi9LdWxpYWgvQmVsYWphckFuZ3VsYXIvSW5zdGFsbEFuZ3VsYXIvUGVtcm9ncmFtYW4tV2ViLUxhbmp1dC9QcmFrdGlrdW0gMTIvc3JjL2FwcC9zaWdudXAvc2lnbnVwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovS3VsaWFoL0JlbGFqYXJBbmd1bGFyL0luc3RhbGxBbmd1bGFyL1BlbXJvZ3JhbWFuLVdlYi1MYW5qdXQvUHJha3Rpa3VtIDEyL3NyYy9hcHAvc2lnbnVwL3NpZ251cC5jb21wb25lbnQudHMuU2lnbnVwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XG4gIHNpZ251cCB3b3JrcyFcbjwvcD5cbiIsIjxhcHAtc2lnbnVwPjwvYXBwLXNpZ251cD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLDRDQUVDO01BQUE7OztvQkNGSjtNQUFBO2dDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
